server:
  port: 8081
spring:
  application:
    name: "requests-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: "localhost"
    port: 5433
    database: "requests_db"
    schema: "public"
    username: "postgres"
    password: "pass123"
jwt:
  secret: bXludWV2YWtleXN1cGVyc2VndXJhY3JlZGl5YWRvdGNvbXByYWdt