name: crediya-csversion

services:
  postgres-db:
    image: postgres:16.8
    container_name: crediya-db
    restart: always
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: requests_db
    ports:
      - "5432:5432"
